### ISSUE TITLE
Missing arm64e Architecture Slice in libaom.a

### ISSUE THREAD

**Issue by adrienreveleau** [awxkee/libaom.swift#1]
**Issue: Missing `arm64e` Architecture Slice in `libaom.a`**

**Context:**

- **Device:** My Mac (Apple Silicon - M1)
- **Xcode Build Number:** 15.0 (24A335)
- **Architecture:** arm64e

**Error:**

When trying to use `libaom.a` in my project, I encounter the following error during Xcode preview:

```
LLVMError: LLVMError(description: "Universal binary /Users/said/Library/Developer/Xcode/DerivedData/square-bjhiwepyapcbtqedgyjvvpzuishs/Build/Products/Debug/libaom.a does not contain a slice for arm64e-apple-macosx21.1")
```

**Description:**

It appears that the provided XCFramework `libaom.a` does not include support for the `arm64e` architecture, which is required for Apple Silicon-based Macs during preview rendering and some builds. This causes issues when using the framework on a Mac with the `arm64e` architecture.

**Steps to Reproduce:**

1. Add `libaom.a` to an Xcode project.
2. Try to render a SwiftUI preview or build for a device that uses the `arm64e` architecture.
3. The error will be thrown due to missing `arm64e` slice.

**Expected Behavior:**

The library should include support for the `arm64e` slice to allow smooth usage across all Apple Silicon devices and during SwiftUI previews.

**Environment:**

- macOS 15.x (Apple Silicon M1)
- Xcode 16.x

**Request:**

Could you please update the XCFramework to include support for `arm64e`? This would greatly improve compatibility on Apple Silicon machines.

Thank you for your time and effort in maintaining this project!

**Comment by awxkee** [comment]
Can confirm it.

However, it will take some time since you're probably using `avif.swift` and there are a lot of libs to rebuild and test.

**Comment by awxkee** [comment]
Should be done in last version
